name: ppp_hackthon
description: "NoPoi task and expense manager."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^19.5.0
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  timezone: ^0.10.1
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/room.png
    - assets/sounds/poi.mp3
    - assets/images/logo.png